version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Run Tests
          command: bundle exec ruby ./Test/kottke_test.rb 
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST -p $PORT  "cd ~/kvideo && git checkout master && git pull && ~/.rbenv/shims/bundle install"

workflows:
 version: 2.1
 build-and-deploy:
   jobs:
     - build
     - deploy:
         requires:
           - build
         filters:
           branches:
             only: master
